# Generated by Django 4.2.1 on 2023-05-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concurrent_django", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
    ]
